# Generated by Django 4.2 on 2024-11-03 22:22

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[events.models.validate_image_extension], verbose_name='Image Field'),
        ),
    ]
