# Generated by Django 4.2 on 2024-11-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
